# Generated by Django 5.2.17 on 2026-08-29 03:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], help_text='ISO 4217 code.', max_length=3, unique=True)),
                ('usd_per_unit', models.DecimalField(decimal_places=8, help_text='USD value of one unit of this currency.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
            ],
            options={
                'verbose_name': 'FX rate',
                'verbose_name_plural': 'FX rates',
                'ordering': ['currency'],
            },
        ),
    ]
