# Generated by Django 5.2.17 on 2026-08-29 03:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(help_text='Human-readable identifier issued by HR.', max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 code.', max_length=2, validators=[django.core.validators.RegexValidator(message='Country must be an uppercase ISO 3166-1 alpha-2 code, e.g. IN.', regex='^[A-Z]{2}$')])),
                ('joined_on', models.DateField()),
                ('salary_amount', models.DecimalField(decimal_places=2, help_text="Gross annual salary in the employee's local currency.", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('salary_usd', models.DecimalField(decimal_places=2, help_text='salary_amount normalised to USD at write time.', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['country'], name='employee_country_idx'), models.Index(fields=['department'], name='employee_department_idx'), models.Index(fields=['last_name', 'first_name'], name='employee_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('salary_amount__gte', 0)), name='employee_salary_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('old_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('SGD', 'Singapore Dollar'), ('BRL', 'Brazilian Real'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar')], max_length=3)),
                ('changed_by', models.CharField(help_text='Username of the actor, or a system identifier for imports.', max_length=254)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_changes', to='employees.employee')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['employee', '-changed_at'], name='salarychange_history_idx')],
            },
        ),
    ]
